
# Profiles =====================

[profiles.trace-playwright]
output-dir = { expr = "f'results/trace-pw/run-{datetime.now().strftime(\"%d-%m-%Y-%H.%M.%S\")}'" }

[profiles.trace-playwright.extend-variables]
MODE = "Playwright"

[profiles.trace-browser]
output-dir = { expr = "f'results/trace-browser/run-{datetime.now().strftime(\"%d-%m-%Y-%H.%M.%S\")}'" }

[profiles.trace-browser.extend-variables]
MODE = "Browser"

[profiles.trace-full]
output-dir = { expr = "f'results/trace-full/run-{datetime.now().strftime(\"%d-%m-%Y-%H.%M.%S\")}'" }

[profiles.trace-full.extend-variables]
MODE = "Full"
